package com.zed3.sipua.welcome;

public class DeviceInfo {
	public static boolean AUTORUN_REMOTE = false;
	public static String AutoVNoName;
	public static int CONFIG_AUDIO_MODE = 0;
	public static boolean CONFIG_CHECK_UPGRADE = false;
	public static String CONFIG_CONFIG_URL;
	public static int CONFIG_LOCAL_LOCATE_MODE = 0;
	public static int CONFIG_MAP_TYPE = 0;
	public static int CONFIG_PPT_CLASSIC = 0;
	public static boolean CONFIG_SUPPORT_AEC = false;
	public static boolean CONFIG_SUPPORT_AUDIO = false;
	public static boolean CONFIG_SUPPORT_AUDIO_CONFERENCE = false;
	public static boolean CONFIG_SUPPORT_AUDIO_SINGLE = false;
	public static boolean CONFIG_SUPPORT_AUTOLOGIN = false;
	public static boolean CONFIG_SUPPORT_AUTORUN = false;
	public static boolean CONFIG_SUPPORT_BLUETOOTH = false;
	public static boolean CONFIG_SUPPORT_EMERGENYCALL = false;
	public static boolean CONFIG_SUPPORT_ENCRYPT = false;
	public static boolean CONFIG_SUPPORT_HOMEKEY_BLOCK = false;
	public static boolean CONFIG_SUPPORT_IM = false;
	public static boolean CONFIG_SUPPORT_LOG = false;
	public static boolean CONFIG_SUPPORT_NS = false;
	public static boolean CONFIG_SUPPORT_PICTURE_UPLOAD = false;
	public static boolean CONFIG_SUPPORT_PTTMAP = false;
	public static boolean CONFIG_SUPPORT_RATE_MONITOR = false;
	public static boolean CONFIG_SUPPORT_REGISTER_INTERNAL = false;
	public static boolean CONFIG_SUPPORT_UNICOM_FLOWSTATISTICS = false;
	public static boolean CONFIG_SUPPORT_UNICOM_PASSWORD = false;
	public static boolean CONFIG_SUPPORT_VAD = false;
	public static boolean CONFIG_SUPPORT_VIDEO = false;
	public static boolean CONFIG_SUPPORT_VIDEO_SINGLE = false;
	public static String CONFIG_UPDATE_URL;
	public static int CONFIG_VIDEO_MONITOR = 0;
	public static int CONFIG_VIDEO_UPLOAD = 0;
	public static boolean ENCRYPT_REMOTE = false;
	public static int GPS_REMOTE = 0;
	public static int GQT_MAIL_LIST = 0;
	public static String IMEI;
	public static String IMSI;
	public static boolean ISAlarmShowing = false;
	public static final int LOCATE_MODE_BAIDU_AUTO = 1;
	public static final int LOCATE_MODE_BAIDU_GPS = 2;
	public static final int LOCATE_MODE_GOOGLE = 4;
	public static final int LOCATE_MODE_NONE = 3;
	public static final int LOCATE_MODE_PHONE_GPS = 0;
	public static String MACADDRESS;
	public static String MANUAL_CONFIG_URL;
	public static final int MAP_TYPE_BAIDU = 0;
	public static final int MAP_TYPE_GOOGLE = 1;
	public static String PHONENUM;
	public static String SIMID;
	public static String SIMNUM;
	public static int TALK_BACK;
	public static String TELNUM;
	public static String UDID;
	public static String UNAME;
	public static int VIDEO_RETRUN_RECORD;
	public static String defaultrecnum;
	public static String http_port;
	public static String https_port;
	public static boolean isEmergency;
	public static boolean isSameHandset;
	public static boolean isSameSimCard;
	public static boolean isSupportHWChange;
	public static String svpnumber;

	static {
		DeviceInfo.IMEI = "";
		DeviceInfo.IMSI = "";
		DeviceInfo.SIMID = "";
		DeviceInfo.TELNUM = "";
		DeviceInfo.MACADDRESS = "";
		DeviceInfo.UDID = "";
		DeviceInfo.UNAME = "";
		DeviceInfo.PHONENUM = "";
		DeviceInfo.SIMNUM = "";
		DeviceInfo.AutoVNoName = "";
		DeviceInfo.isSameSimCard = false;
		DeviceInfo.isSameHandset = false;
		DeviceInfo.svpnumber = "";
		DeviceInfo.defaultrecnum = "";
		DeviceInfo.http_port = "";
		DeviceInfo.https_port = "";
		DeviceInfo.CONFIG_UPDATE_URL = "";
		DeviceInfo.CONFIG_CONFIG_URL = "";
		DeviceInfo.CONFIG_SUPPORT_AUTOLOGIN = true;
		DeviceInfo.CONFIG_SUPPORT_UNICOM_PASSWORD = false;
		DeviceInfo.CONFIG_SUPPORT_UNICOM_FLOWSTATISTICS = false;
		DeviceInfo.CONFIG_SUPPORT_VIDEO = true;
		DeviceInfo.CONFIG_SUPPORT_AUDIO = true;
		DeviceInfo.CONFIG_SUPPORT_VIDEO_SINGLE = true;
		DeviceInfo.CONFIG_SUPPORT_AUDIO_SINGLE = true;
		DeviceInfo.CONFIG_AUDIO_MODE = 1;
		DeviceInfo.CONFIG_SUPPORT_AUTORUN = false;
		DeviceInfo.CONFIG_CHECK_UPGRADE = true;
		DeviceInfo.CONFIG_SUPPORT_ENCRYPT = false;
		DeviceInfo.CONFIG_SUPPORT_PTTMAP = false;
		DeviceInfo.CONFIG_VIDEO_MONITOR = 0;
		DeviceInfo.CONFIG_VIDEO_UPLOAD = 0;
		DeviceInfo.CONFIG_PPT_CLASSIC = 1;
		DeviceInfo.CONFIG_SUPPORT_AUDIO_CONFERENCE = false;
		DeviceInfo.CONFIG_SUPPORT_PICTURE_UPLOAD = true;
		DeviceInfo.CONFIG_SUPPORT_IM = true;
		DeviceInfo.CONFIG_SUPPORT_EMERGENYCALL = true;
		DeviceInfo.CONFIG_SUPPORT_HOMEKEY_BLOCK = false;
		DeviceInfo.CONFIG_SUPPORT_VAD = false;
		DeviceInfo.CONFIG_SUPPORT_LOG = false;
		DeviceInfo.CONFIG_SUPPORT_RATE_MONITOR = true;
		DeviceInfo.CONFIG_SUPPORT_REGISTER_INTERNAL = true;
		DeviceInfo.CONFIG_SUPPORT_AEC = true;
		DeviceInfo.CONFIG_SUPPORT_NS = true;
		DeviceInfo.CONFIG_SUPPORT_BLUETOOTH = false;
		DeviceInfo.CONFIG_MAP_TYPE = 0;
		DeviceInfo.CONFIG_LOCAL_LOCATE_MODE = 4;
		DeviceInfo.GQT_MAIL_LIST = 1;
		DeviceInfo.VIDEO_RETRUN_RECORD = 1;
		DeviceInfo.TALK_BACK = 1;
		DeviceInfo.GPS_REMOTE = -1;
		DeviceInfo.ENCRYPT_REMOTE = false;
		DeviceInfo.AUTORUN_REMOTE = true;
		DeviceInfo.isSupportHWChange = false;
		DeviceInfo.MANUAL_CONFIG_URL = "";
	}
}
